services:

  consul:
    container_name: infytel-consul
    image: hashicorp/consul:1.20.4
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - consul-data:/consul/data
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0 -bind=0.0.0.0
    networks:
      - infytel-network
    restart: unless-stopped

  postgres:
    container_name: infytel_postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - infytel_DB:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - infytel-network
    restart: unless-stopped

  pgadmin:
    container_name: infytel_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - infytel_pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - infytel-network
    restart: unless-stopped


  calldetailsms:
    container_name: calldetailsms
    image: calldetailsms:v1
    ports:
      - 9100:9100
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONSUL_HOST=consul
    depends_on:
      - postgres
      - consul
    networks:
      - infytel-network

  customerms:
    container_name: customerms
    image: customerms:v1
    ports:
      - 9200:9200
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONSUL_HOST=consul
    depends_on:
      - postgres
      - consul
    networks:
      - infytel-network

  friend-familyms:
    container_name: friend-familyms
    image: friend-familyms:v1
    ports:
      - 9300:9300
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONSUL_HOST=consul
    depends_on:
      - postgres
      - consul
    networks:
      - infytel-network

  planms:
    container_name: planms
    image: planms:v1
    ports:
      - 9400:9400
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONSUL_HOST=consul
    depends_on:
      - postgres
      - consul
    networks:
      - infytel-network

  infytel-gateway:
    container_name: infytel-gateway
    image: infytel-gateway:v1
    ports:
      - 9500:9500
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONSUL_HOST=consul
    depends_on:
      - postgres
      - consul
    networks:
      - infytel-network