services:

  consul:
    container_name: infytel-docker-consul
    hostname: consul
    image: hashicorp/consul:latest
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0 -bind=0.0.0.0
    ports:
      - "8550:8500"
      - "8650:8600/udp"
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - infytel-docker-consul-data:/consul/data
    networks:
      - infytel-network
    restart: unless-stopped

  postgres:
    container_name: infytel_postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - infytel_DB:/data/postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - infytel-network
    restart: unless-stopped

  pgadmin:
    container_name: infytel_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - infytel_pgadmin:/var/lib/pgadmin
    ports:
      - "5200:80"
    networks:
      - infytel-network
    restart: unless-stopped

  calldetailsms:
    container_name: calldetailsms
    image: eugenekwaka/infytel_calldetailsms:latest
    ports:
      - 9100:9100
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
    depends_on:
      postgres:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - infytel-network

  customerms:
    container_name: customerms
    image: eugenekwaka/infytel_customerms:latest
    ports:
      - 9200:9200
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
    depends_on:
      postgres:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - infytel-network

  friend-familyms:
    container_name: friend-familyms
    image: eugenekwaka/infytel_friend-familyms:latest
    ports:
      - 9300:9300
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
    depends_on:
      postgres:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - infytel-network

  planms:
    container_name: planms
    image: eugenekwaka/infytel_planms:latest
    ports:
      - 9400:9400
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
    depends_on:
      postgres:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - infytel-network

  gateway:
    container_name: api-gateway
    image: eugenekwaka/infytel_gateway:latest
    ports:
      - 9500:9500
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
    depends_on:
      postgres:
        condition: service_healthy
      consul:
        condition: service_healthy
    networks:
      - infytel-network

volumes:
  infytel-docker-consul-data:
  infytel_DB:
  infytel_pgadmin:

networks:
  infytel-network:
